# Generated by Django 3.0.4 on 2020-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('referrer', models.CharField(max_length=40)),
                ('isAnswered', models.BooleanField()),
            ],
        ),
    ]
