# Generated by Django 3.0.4 on 2020-04-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200408_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='isTestLead',
            field=models.BooleanField(default=False),
        ),
    ]
